const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "Crypto Wallet API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  servers: [
    {
      url: "http://localhost:4000/todos", // url
      description: "Local server", // name
    },
  ],
  tags: [
    {
      name: "Coin",
      description: "Endpoints related to cryptocurrency coin",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    coins: [
      {
        id: "63adca139058b746f2c8e5bd",
        name: "Bitcoin",
        code: "BTC",
        price: 16616.2,
        icon: "http://localhost:3000/coins/icon/btc",
      },
    ],
    coin: {
      id: "63adca139058b746f2c8e5bd",
      name: "Bitcoin",
      code: "BTC",
      price: 16616.2,
      icon: "http://localhost:3000/coins/icon/btc",
    },
    md5: { md5: "63adca139058b746f2c8e5bd" },
    createCoin: {
      name: "Bitcoin",
      code: "BTC",
      price: 16616.2,
      icon: "http://localhost:3000/coins/icon/btc",
    },
    updateCoin: {
      name: "Bitcoin",
      code: "BTC",
      price: 16616.2,
      icon: "http://localhost:3000/coins/icon/btc",
    },
    // User: {
    //   name: "Jhon Doe",
    //   age: 29,
    //   parents: {
    //     $ref: "#/definitions/Parents",
    //   },
    //   diplomas: [
    //     {
    //       school: "XYZ University",
    //       year: 2020,
    //       completed: true,
    //       internship: {
    //         hours: 290,
    //         location: "XYZ Company",
    //       },
    //     },
    //   ],
    // },
    // AddUser: {
    //   $name: "Jhon Doe",
    //   $age: 29,
    //   about: "",
    // },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./src/server.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./src/server"); // Your project's root file
});
